#ifndef CONFIGURA_GERAL_H
#define CONFIGURA_GERAL_H

#define KEYPAD_ROW0_PIN 4
#define KEYPAD_ROW1_PIN 8
#define KEYPAD_ROW2_PIN 9
#define KEYPAD_ROW3_PIN 16
#define KEYPAD_COL0_PIN 17
#define KEYPAD_COL1_PIN 18
#define KEYPAD_COL2_PIN 19
#define KEYPAD_COL3_PIN 20


#endif // CONFIGURA_GERAL_H
